# application.yml

spring:
  application:
    name: gathertree-demo-backend

  profiles:
    active: local

server:
  port: 8080

gathertree:
  redis:
    tree-ttl-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: health
